language: php

dist: trusty
sudo: false

cache:
  directories:
    - $(composer global config --list | grep "\[cache-files-dir\]" | cut -d  " " -f 3 | tr -d '()')

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  - hhvm-3.3
  - hhvm-3.6
  - hhvm-3.9
  - hhvm-3.12
  - hhvm-3.15
  - hhvm-3.18
  - nightly
  - hhvm-nightly

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm-nightly

  include:
    - php: 5.3
      dist: precise
      env: DEPENDENCIES="high"

    - php: 5.3
      dist: precise
      env: DEPENDENCIES="low"

    - php: hhvm
      env: DEPENDENCIES="hhvm_high"

    - php: hhvm-3.12
      env: DEPENDENCIES="hhvm_high"

    - php: hhvm-3.15
      env: DEPENDENCIES="hhvm_high"

    - php: hhvm-3.18
      env: DEPENDENCIES="hhvm_high"

    - php: hhvm-nightly
      env: DEPENDENCIES="hhvm_high"

install:
  - mv .git ~.git
  - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update --no-interaction --prefer-stable; fi
  - if [[ "$DEPENDENCIES" = 'hhvm_high' ]]; then bin/composer-set-config.php php $(php -d hhvm.php7.all=1 -r "echo PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION;") && travis_retry composer update --no-interaction --prefer-stable; fi
  - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry composer update --no-interaction --prefer-stable --prefer-lowest; fi
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then
      export PHP_CS_FIXER="./dev-tools/vendor/bin/php-cs-fixer";
      export RUN_CS_FIXER="true";
    fi
  # https://travis-ci.org/awesomite/var-dumper/jobs/428682342
  # Warning: ini_get_all() expects parameter 1 to be string,
  # null given in /home/travis/build/awesomite/var-dumper/vendor/phpunit/phpunit/src/Util/GlobalState.php on line 79
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:4} == "hhvm" ]]; then
      export PHPUNIT_EXCLUDE="--exclude-group=syntax-test";
    fi
  - cd dev-tools; travis_retry composer update; cd ..

before_script:
  - vendor/bin/phpunit-4.8-fixer
  - if [[ "$DEPENDENCIES" = 'hhvm_high' ]]; then echo 'hhvm.php7.all=1' >> /etc/hhvm/php.ini; fi
  - if [[ "$DEPENDENCIES" = 'low' ]]; then export PHP_ARGS=$(php -r "echo '-d error_reporting=', E_ALL ^ (E_DEPRECATED | E_USER_DEPRECATED);"); else export PHP_ARGS=''; fi

script:
  - if [[ "$RUN_CS_FIXER" = "true" ]]; then php -n ${PHP_CS_FIXER} --diff --dry-run -v --allow-risky=yes fix; fi
  - php ${PHP_ARGS} vendor/bin/phpunit ${PHPUNIT_EXCLUDE}
  - MODE_SPEED_TEST=true php ${PHP_ARGS} vendor/bin/phpunit ${PHPUNIT_EXCLUDE}
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then
      wget https://github.com/infection/infection/releases/download/0.10.3/infection.phar;
      wget https://github.com/infection/infection/releases/download/0.10.3/infection.phar.asc;
      gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 493B4AA0
      gpg --with-fingerprint --verify infection.phar.asc infection.phar
      chmod +x infection.phar;
      ./infection.phar
    fi
  - php examples/big-dump.php
  - php examples/binary-string.php
  - php examples/closure.php
  - php examples/custom-indent.php
  - php examples/debug-info.php
  - php examples/dumper.php
  - php examples/exception.php
  - php -r 'exit(version_compare(PHP_VERSION, '5.6') >= 0 ? 0 : 1);' && php examples/exception-variadic.php || echo 'PHP >= 5.6 required'
  - php examples/object.php
  - php examples/simple-array.php

after_script:
  - mv ~.git .git
  - travis_retry bin/coveralls.sh
